// This file is generated by Simplicity Studio.  Please do not edit manually.
//
//

// Enclosing macro to prevent multiple inclusion
#ifndef __AF_GEN_EVENT__
#define __AF_GEN_EVENT__


// Code used to configure the cluster event mechanism
#define EMBER_AF_GENERATED_EVENT_CODE \
  EmberEventControl emberAfIdentifyClusterServerTickCallbackControl1; \
  EmberEventControl emberAfIdentifyClusterServerTickCallbackControl2; \
  EmberEventControl emberAfIdentifyClusterServerTickCallbackControl3; \
  EmberEventControl emberAfIdentifyClusterServerTickCallbackControl4; \
  EmberEventControl emberAfIdentifyClusterServerTickCallbackControl5; \
  EmberEventControl emberAfIdentifyClusterServerTickCallbackControl6; \
  EmberEventControl emberAfIdentifyClusterServerTickCallbackControl7; \
  EmberEventControl emberAfIdentifyClusterServerTickCallbackControl8; \
  EmberEventControl emberAfIdentifyClusterServerTickCallbackControl9; \
  EmberEventControl emberAfIdentifyClusterServerTickCallbackControl10; \
  EmberEventControl emberAfIdentifyClusterServerTickCallbackControl11; \
  EmberEventControl emberAfIdentifyClusterServerTickCallbackControl12; \
  EmberEventControl emberAfIasZoneClusterServerTickCallbackControl12; \
  EmberEventControl emberAfIdentifyClusterServerTickCallbackControl13; \
  EmberEventControl emberAfIasZoneClusterServerTickCallbackControl13; \
  extern EmberEventControl TimerCheckHoldControl; \
  extern EmberEventControl TimerCheckPressControl; \
  extern EmberEventControl TimerPrintTableAddressControl; \
  extern EmberEventControl TimerProcessDataControl; \
  extern EmberEventControl TimerSendStatusOverLCDControl; \
  extern EmberEventControl TimerSendStatusOverUARTControl; \
  extern EmberEventControl commissioningLedEventControl; \
  extern EmberEventControl emberAfPluginFindAndBindInitiatorCheckTargetResponsesEventControl; \
  extern EmberEventControl emberAfPluginIasZoneClientStateMachineEventControl; \
  extern EmberEventControl emberAfPluginIasZoneServerManageQueueEventControl; \
  extern EmberEventControl emberAfPluginInterpanFragmentReceiveEventControl; \
  extern EmberEventControl emberAfPluginInterpanFragmentTransmitEventControl; \
  extern EmberEventControl emberAfPluginNetworkCreatorSecurityOpenNetworkEventControl; \
  extern EmberEventControl emberAfPluginNetworkSteeringFinishSteeringEventControl; \
  extern EmberEventControl emberAfPluginReportingTickEventControl; \
  extern EmberEventControl emberAfPluginScanDispatchScanEventControl; \
  extern EmberEventControl emberAfPluginUpdateTcLinkKeyBeginTcLinkKeyUpdateEventControl; \
  extern EmberEventControl findingAndBindingEventControl; \
  extern void TimerCheckHoldHandler(void); \
  extern void TimerCheckPressHandler(void); \
  extern void TimerPrintTableAddressHandler(void); \
  extern void TimerProcessDataHandler(void); \
  extern void TimerSendStatusOverLCDHandler(void); \
  extern void TimerSendStatusOverUARTHandler(void); \
  extern void commissioningLedEventHandler(void); \
  extern void emberAfPluginFindAndBindInitiatorCheckTargetResponsesEventHandler(void); \
  extern void emberAfPluginIasZoneClientStateMachineEventHandler(void); \
  extern void emberAfPluginIasZoneServerManageQueueEventHandler(void); \
  extern void emberAfPluginInterpanFragmentReceiveEventHandler(void); \
  extern void emberAfPluginInterpanFragmentTransmitEventHandler(void); \
  extern void emberAfPluginNetworkCreatorSecurityOpenNetworkEventHandler(void); \
  extern void emberAfPluginNetworkSteeringFinishSteeringEventHandler(void); \
  extern void emberAfPluginReportingTickEventHandler(void); \
  extern void emberAfPluginScanDispatchScanEventHandler(void); \
  extern void emberAfPluginUpdateTcLinkKeyBeginTcLinkKeyUpdateEventHandler(void); \
  extern void findingAndBindingEventHandler(void); \
  static void clusterTickWrapper(EmberEventControl *control, EmberAfTickFunction callback, uint8_t endpoint) \
  { \
    emberAfPushEndpointNetworkIndex(endpoint); \
    emberEventControlSetInactive(*control); \
    (*callback)(endpoint); \
    emberAfPopNetworkIndex(); \
  } \
  void emberAfIdentifyClusterServerTickCallbackWrapperFunction1(void) { clusterTickWrapper(&emberAfIdentifyClusterServerTickCallbackControl1, emberAfIdentifyClusterServerTickCallback, 1); } \
  void emberAfIdentifyClusterServerTickCallbackWrapperFunction2(void) { clusterTickWrapper(&emberAfIdentifyClusterServerTickCallbackControl2, emberAfIdentifyClusterServerTickCallback, 2); } \
  void emberAfIdentifyClusterServerTickCallbackWrapperFunction3(void) { clusterTickWrapper(&emberAfIdentifyClusterServerTickCallbackControl3, emberAfIdentifyClusterServerTickCallback, 3); } \
  void emberAfIdentifyClusterServerTickCallbackWrapperFunction4(void) { clusterTickWrapper(&emberAfIdentifyClusterServerTickCallbackControl4, emberAfIdentifyClusterServerTickCallback, 4); } \
  void emberAfIdentifyClusterServerTickCallbackWrapperFunction5(void) { clusterTickWrapper(&emberAfIdentifyClusterServerTickCallbackControl5, emberAfIdentifyClusterServerTickCallback, 5); } \
  void emberAfIdentifyClusterServerTickCallbackWrapperFunction6(void) { clusterTickWrapper(&emberAfIdentifyClusterServerTickCallbackControl6, emberAfIdentifyClusterServerTickCallback, 6); } \
  void emberAfIdentifyClusterServerTickCallbackWrapperFunction7(void) { clusterTickWrapper(&emberAfIdentifyClusterServerTickCallbackControl7, emberAfIdentifyClusterServerTickCallback, 7); } \
  void emberAfIdentifyClusterServerTickCallbackWrapperFunction8(void) { clusterTickWrapper(&emberAfIdentifyClusterServerTickCallbackControl8, emberAfIdentifyClusterServerTickCallback, 8); } \
  void emberAfIdentifyClusterServerTickCallbackWrapperFunction9(void) { clusterTickWrapper(&emberAfIdentifyClusterServerTickCallbackControl9, emberAfIdentifyClusterServerTickCallback, 9); } \
  void emberAfIdentifyClusterServerTickCallbackWrapperFunction10(void) { clusterTickWrapper(&emberAfIdentifyClusterServerTickCallbackControl10, emberAfIdentifyClusterServerTickCallback, 10); } \
  void emberAfIdentifyClusterServerTickCallbackWrapperFunction11(void) { clusterTickWrapper(&emberAfIdentifyClusterServerTickCallbackControl11, emberAfIdentifyClusterServerTickCallback, 11); } \
  void emberAfIdentifyClusterServerTickCallbackWrapperFunction12(void) { clusterTickWrapper(&emberAfIdentifyClusterServerTickCallbackControl12, emberAfIdentifyClusterServerTickCallback, 12); } \
  void emberAfIasZoneClusterServerTickCallbackWrapperFunction12(void) { clusterTickWrapper(&emberAfIasZoneClusterServerTickCallbackControl12, emberAfIasZoneClusterServerTickCallback, 12); } \
  void emberAfIdentifyClusterServerTickCallbackWrapperFunction13(void) { clusterTickWrapper(&emberAfIdentifyClusterServerTickCallbackControl13, emberAfIdentifyClusterServerTickCallback, 13); } \
  void emberAfIasZoneClusterServerTickCallbackWrapperFunction13(void) { clusterTickWrapper(&emberAfIasZoneClusterServerTickCallbackControl13, emberAfIasZoneClusterServerTickCallback, 13); } \


// EmberEventData structs used to populate the EmberEventData table
#define EMBER_AF_GENERATED_EVENTS   \
  { &emberAfIdentifyClusterServerTickCallbackControl1, emberAfIdentifyClusterServerTickCallbackWrapperFunction1 }, \
  { &emberAfIdentifyClusterServerTickCallbackControl2, emberAfIdentifyClusterServerTickCallbackWrapperFunction2 }, \
  { &emberAfIdentifyClusterServerTickCallbackControl3, emberAfIdentifyClusterServerTickCallbackWrapperFunction3 }, \
  { &emberAfIdentifyClusterServerTickCallbackControl4, emberAfIdentifyClusterServerTickCallbackWrapperFunction4 }, \
  { &emberAfIdentifyClusterServerTickCallbackControl5, emberAfIdentifyClusterServerTickCallbackWrapperFunction5 }, \
  { &emberAfIdentifyClusterServerTickCallbackControl6, emberAfIdentifyClusterServerTickCallbackWrapperFunction6 }, \
  { &emberAfIdentifyClusterServerTickCallbackControl7, emberAfIdentifyClusterServerTickCallbackWrapperFunction7 }, \
  { &emberAfIdentifyClusterServerTickCallbackControl8, emberAfIdentifyClusterServerTickCallbackWrapperFunction8 }, \
  { &emberAfIdentifyClusterServerTickCallbackControl9, emberAfIdentifyClusterServerTickCallbackWrapperFunction9 }, \
  { &emberAfIdentifyClusterServerTickCallbackControl10, emberAfIdentifyClusterServerTickCallbackWrapperFunction10 }, \
  { &emberAfIdentifyClusterServerTickCallbackControl11, emberAfIdentifyClusterServerTickCallbackWrapperFunction11 }, \
  { &emberAfIdentifyClusterServerTickCallbackControl12, emberAfIdentifyClusterServerTickCallbackWrapperFunction12 }, \
  { &emberAfIasZoneClusterServerTickCallbackControl12, emberAfIasZoneClusterServerTickCallbackWrapperFunction12 }, \
  { &emberAfIdentifyClusterServerTickCallbackControl13, emberAfIdentifyClusterServerTickCallbackWrapperFunction13 }, \
  { &emberAfIasZoneClusterServerTickCallbackControl13, emberAfIasZoneClusterServerTickCallbackWrapperFunction13 }, \
  { &TimerCheckHoldControl, TimerCheckHoldHandler }, \
  { &TimerCheckPressControl, TimerCheckPressHandler }, \
  { &TimerPrintTableAddressControl, TimerPrintTableAddressHandler }, \
  { &TimerProcessDataControl, TimerProcessDataHandler }, \
  { &TimerSendStatusOverLCDControl, TimerSendStatusOverLCDHandler }, \
  { &TimerSendStatusOverUARTControl, TimerSendStatusOverUARTHandler }, \
  { &commissioningLedEventControl, commissioningLedEventHandler }, \
  { &emberAfPluginFindAndBindInitiatorCheckTargetResponsesEventControl, emberAfPluginFindAndBindInitiatorCheckTargetResponsesEventHandler }, \
  { &emberAfPluginIasZoneClientStateMachineEventControl, emberAfPluginIasZoneClientStateMachineEventHandler }, \
  { &emberAfPluginIasZoneServerManageQueueEventControl, emberAfPluginIasZoneServerManageQueueEventHandler }, \
  { &emberAfPluginInterpanFragmentReceiveEventControl, emberAfPluginInterpanFragmentReceiveEventHandler }, \
  { &emberAfPluginInterpanFragmentTransmitEventControl, emberAfPluginInterpanFragmentTransmitEventHandler }, \
  { &emberAfPluginNetworkCreatorSecurityOpenNetworkEventControl, emberAfPluginNetworkCreatorSecurityOpenNetworkEventHandler }, \
  { &emberAfPluginNetworkSteeringFinishSteeringEventControl, emberAfPluginNetworkSteeringFinishSteeringEventHandler }, \
  { &emberAfPluginReportingTickEventControl, emberAfPluginReportingTickEventHandler }, \
  { &emberAfPluginScanDispatchScanEventControl, emberAfPluginScanDispatchScanEventHandler }, \
  { &emberAfPluginUpdateTcLinkKeyBeginTcLinkKeyUpdateEventControl, emberAfPluginUpdateTcLinkKeyBeginTcLinkKeyUpdateEventHandler }, \
  { &findingAndBindingEventControl, findingAndBindingEventHandler }, \


#define EMBER_AF_GENERATED_EVENT_STRINGS   \
  "Identify Cluster Server EP 1",  \
  "Identify Cluster Server EP 2",  \
  "Identify Cluster Server EP 3",  \
  "Identify Cluster Server EP 4",  \
  "Identify Cluster Server EP 5",  \
  "Identify Cluster Server EP 6",  \
  "Identify Cluster Server EP 7",  \
  "Identify Cluster Server EP 8",  \
  "Identify Cluster Server EP 9",  \
  "Identify Cluster Server EP 10",  \
  "Identify Cluster Server EP 11",  \
  "Identify Cluster Server EP 12",  \
  "IAS Zone Cluster Server EP 12",  \
  "Identify Cluster Server EP 13",  \
  "IAS Zone Cluster Server EP 13",  \
  "Timer check hold control",  \
  "Timer check press control",  \
  "Timer print table address control",  \
  "Timer process data control",  \
  "Event data",  \
  "Timer send status over u a r t control",  \
  "Commissioning led event control",  \
  "Find and Bind Initiator Plugin CheckTargetResponses",  \
  "IAS Zone Client Plugin StateMachine",  \
  "IAS Zone Server Plugin ManageQueue",  \
  "Interpan Plugin FragmentReceive",  \
  "Interpan Plugin FragmentTransmit",  \
  "Network Creator Security Plugin OpenNetwork",  \
  "Network Steering Plugin FinishSteering",  \
  "Reporting Plugin Tick",  \
  "Scan Dispatch Plugin Scan",  \
  "Update TC Link Key Plugin BeginTcLinkKeyUpdate",  \
  "Finding and binding event control",  \


// The length of the event context table used to track and retrieve cluster events
#define EMBER_AF_EVENT_CONTEXT_LENGTH 15

// EmberAfEventContext structs used to populate the EmberAfEventContext table
#define EMBER_AF_GENERATED_EVENT_CONTEXT { 0x1, 0x3, false, EMBER_AF_LONG_POLL, EMBER_AF_OK_TO_SLEEP, &emberAfIdentifyClusterServerTickCallbackControl1}, \
{ 0x2, 0x3, false, EMBER_AF_LONG_POLL, EMBER_AF_OK_TO_SLEEP, &emberAfIdentifyClusterServerTickCallbackControl2}, \
{ 0x3, 0x3, false, EMBER_AF_LONG_POLL, EMBER_AF_OK_TO_SLEEP, &emberAfIdentifyClusterServerTickCallbackControl3}, \
{ 0x4, 0x3, false, EMBER_AF_LONG_POLL, EMBER_AF_OK_TO_SLEEP, &emberAfIdentifyClusterServerTickCallbackControl4}, \
{ 0x5, 0x3, false, EMBER_AF_LONG_POLL, EMBER_AF_OK_TO_SLEEP, &emberAfIdentifyClusterServerTickCallbackControl5}, \
{ 0x6, 0x3, false, EMBER_AF_LONG_POLL, EMBER_AF_OK_TO_SLEEP, &emberAfIdentifyClusterServerTickCallbackControl6}, \
{ 0x7, 0x3, false, EMBER_AF_LONG_POLL, EMBER_AF_OK_TO_SLEEP, &emberAfIdentifyClusterServerTickCallbackControl7}, \
{ 0x8, 0x3, false, EMBER_AF_LONG_POLL, EMBER_AF_OK_TO_SLEEP, &emberAfIdentifyClusterServerTickCallbackControl8}, \
{ 0x9, 0x3, false, EMBER_AF_LONG_POLL, EMBER_AF_OK_TO_SLEEP, &emberAfIdentifyClusterServerTickCallbackControl9}, \
{ 0xa, 0x3, false, EMBER_AF_LONG_POLL, EMBER_AF_OK_TO_SLEEP, &emberAfIdentifyClusterServerTickCallbackControl10}, \
{ 0xb, 0x3, false, EMBER_AF_LONG_POLL, EMBER_AF_OK_TO_SLEEP, &emberAfIdentifyClusterServerTickCallbackControl11}, \
{ 0xc, 0x3, false, EMBER_AF_LONG_POLL, EMBER_AF_OK_TO_SLEEP, &emberAfIdentifyClusterServerTickCallbackControl12}, \
{ 0xc, 0x500, false, EMBER_AF_LONG_POLL, EMBER_AF_OK_TO_SLEEP, &emberAfIasZoneClusterServerTickCallbackControl12}, \
{ 0xd, 0x3, false, EMBER_AF_LONG_POLL, EMBER_AF_OK_TO_SLEEP, &emberAfIdentifyClusterServerTickCallbackControl13}, \
{ 0xd, 0x500, false, EMBER_AF_LONG_POLL, EMBER_AF_OK_TO_SLEEP, &emberAfIasZoneClusterServerTickCallbackControl13}


#endif // __AF_GEN_EVENT__
